services:
  - type: web
    name: qr-word-cloud-fe
    env: node
    nodeVersion: 20.11.1
    buildCommand: |
      rm -rf node_modules .next && 
      npm ci && 
      npm run build
    startCommand: |
      cp -r .next/static .next/standalone/.next/ && 
      cp -r public .next/standalone/ && 
      cd .next/standalone && 
      node server.js
    envVars:
      - key: NEXT_PUBLIC_WS_URL
        value: wss://qr-word-cloud-be.onrender.com/ws
      - key: NEXT_PUBLIC_API_URL
        value: https://qr-word-cloud-be.onrender.com
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: production
    plan: free 