services:
  - type: web
    name: qr-word-cloud-fe
    env: node
    nodeVersion: 20.11.1
    buildCommand: npm ci && npm run build
    startCommand: cd .next/standalone && node server.js
    envVars:
      - key: NEXT_PUBLIC_WS_URL
        value: wss://qr-word-cloud-be.onrender.com/ws
      - key: NEXT_PUBLIC_API_URL
        value: https://qr-word-cloud-be.onrender.com
      - key: NODE_ENV
        value: production
      - key: HOSTNAME
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
    plan: free 