services:
  - type: web
    name: qr-word-cloud-fe
    env: node
    nodeVersion: 20.11.1
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_WS_URL
        value: wss://api.unveilinglights.it/ws
      - key: NEXT_PUBLIC_API_URL
        value: https://api.unveilinglights.it
      - key: NODE_ENV
        value: production
    plan: free 