services:
  - type: web
    name: qr-word-cloud-fe
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_WS_URL
        value: wss://qr-word-cloud-be.onrender.com/ws
      - key: NEXT_PUBLIC_API_URL
        value: https://qr-word-cloud-be.onrender.com
    plan: free 